export const cakes = [
  {
    name: "Chocolate Cake",
    id: 1,
    desc: "Rich and decadent chocolate cake",
    price: 25.99,
    img: "https://data.thefeedfeed.com/recommended/post_4311548.jpeg",
    rating: 4,
    reviews: 78,
  },
  {
    name: "Vanilla Cake",
    id: 2,
    desc: "Classic vanilla cake with buttercream frosting",
    price: 19.99,
    img: "https://www.recipetineats.com/tachyon/2020/08/My-best-Vanilla-Cake_9.jpg",
    rating: 3,
    reviews: 7,
  },
  {
    name: "Red Velvet Cake",
    id: 3,
    desc: "Velvety red cake with cream cheese frosting",
    price: 22.49,
    img: "https://handletheheat.com/wp-content/uploads/2013/04/red-velvet-cake-recipe-SQUARE.jpg",
    rating: 4,
    reviews: 90,
  },
  {
    name: "Carrot Cake",
    id: 4,
    desc: "Moist carrot cake topped with walnuts",
    price: 18.75,
    img: "https://www.inspiredtaste.net/wp-content/uploads/2017/07/Carrot-Cake-Recipe-5-1200.jpg",
    rating: 2,
    reviews: 2,
  },
  {
    name: "Lemon Blueberry Cake",
    id: 5,
    desc: "Zesty lemon cake with blueberry compote",
    price: 21.99,
    img: "https://bakerholicsanonymous.com/wp-content/uploads/2023/02/screen-shot-2023-02-12-at-12.20.56-pm.png",
    rating: 5,
    reviews: 7,
  },
  {
    name: "Strawberry Shortcake",
    id: 6,
    desc: "Light and fluffy strawberry cake layers",
    price: 20.25,
    img: "https://static01.nyt.com/images/2023/03/13/multimedia/NHJ-Strawberry-Shortcake-qtkw-copy/NHJ-Strawberry-Shortcake-qtkw-superJumbo.jpg",
    rating: 5,
    reviews: 70,
  },
  {
    name: "Coconut Cream Cake",
    id: 7,
    desc: "Coconut-infused cake with whipped cream",
    price: 23.5,
    img: "https://divascancook.com/wp-content/uploads/2023/03/coconut-cream-cake-.jpg",
    rating: 3,
    reviews: 10,
  },
  {
    name: "Black Forest Cake",
    id: 8,
    desc: "Layers of chocolate sponge, cherries, and cream",
    price: 24.75,
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/eggless-black-forest-cake-recipe.jpg",
    rating: 2,
    reviews: 11,
  },
  {
    name: "Blueberry Cheesecake",
    id: 9,
    desc: "Creamy cheesecake with a blueberry topping",
    price: 26.0,
    img: "https://bakewithshivesh.com/wp-content/uploads/2021/05/IMG_9141-scaled.jpg",
    rating: 5,
    reviews: 15,
  },
  {
    name: "Pineapple Upside-Down Cake",
    id: 10,
    desc: "Caramelized pineapple slices on a fluffy cake",
    price: 17.5,
    img: "https://images.immediate.co.uk/production/volatile/sites/30/2019/05/Pineapple-upside-down-cake-32b5bb3.jpg",
    rating: 5,
    reviews: 25,
  },
];
